import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Sidebar } from "../components/Sidebar"; // Import the new Sidebar component

const font = Raleway({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Net",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body className={`dark ${font.className} antialiased`}>
    //     <section className="flex flex-row ml-64 w-full min-h-screen">
    //
    //       <section className="w-full max-w-4xl">{children}</section>
    //     </section>
    //   </body>
    // </html>
    <html lang="en">
      <body className={`dark ${font.className} antialiased`}>
        <main className="flex flex-row items-center min-h-screen">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
