import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { Poppins } from "next/font/google"; // Import Poppins font
import "./globals.css";
import { Sidebar } from "../components/Sidebar"; // Import the Sidebar component

// Initialize fonts
const raleway = Raleway({ weight: "400", subsets: ["latin"] });
const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Net",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className}  antialiased`}>
        <main className="flex flex-row items-center min-h-screen">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
